/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRequestChiefRouteImport } from './routes/_authenticated/request-chief'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as AuthenticatedRequestChiefIndexRouteImport } from './routes/_authenticated/request-chief/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as publicWeeksIndexRouteImport } from './routes/(public)/weeks/index'
import { Route as publicSportsIndexRouteImport } from './routes/(public)/sports/index'
import { Route as publicResultsIndexRouteImport } from './routes/(public)/results/index'
import { Route as publicDelegationsIndexRouteImport } from './routes/(public)/delegations/index'
import { Route as publicCalendarIndexRouteImport } from './routes/(public)/calendar/index'
import { Route as AuthenticatedRequestChiefStatusRouteImport } from './routes/_authenticated/request-chief/status'
import { Route as AuthenticatedDashboardChiefRouteImport } from './routes/_authenticated/dashboard/_chief'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/_admin'
import { Route as AuthenticatedAthletesAthleteIdRouteImport } from './routes/_authenticated/athletes/$athleteId'
import { Route as publicWeeksWeekIdRouteImport } from './routes/(public)/weeks/$weekId'
import { Route as publicSportsSportIdRouteImport } from './routes/(public)/sports/$sportId'
import { Route as publicDelegationsDelegationIdRouteImport } from './routes/(public)/delegations/$delegationId'
import { Route as AuthenticatedDashboardAthletesIndexRouteImport } from './routes/_authenticated/dashboard/athletes/index'
import { Route as AuthenticatedDashboardAthletesNewRouteImport } from './routes/_authenticated/dashboard/athletes/new'
import { Route as AuthenticatedDashboardChiefMyDelegationIndexRouteImport } from './routes/_authenticated/dashboard/_chief/my-delegation/index'
import { Route as AuthenticatedDashboardAdminSportsIndexRouteImport } from './routes/_authenticated/dashboard/_admin/sports/index'
import { Route as AuthenticatedDashboardAdminDelegationsIndexRouteImport } from './routes/_authenticated/dashboard/_admin/delegations/index'
import { Route as AuthenticatedDashboardChiefMyDelegationTransfersRouteImport } from './routes/_authenticated/dashboard/_chief/my-delegation/transfers'
import { Route as AuthenticatedDashboardChiefMyDelegationMembersRouteImport } from './routes/_authenticated/dashboard/_chief/my-delegation/members'
import { Route as AuthenticatedDashboardChiefMyDelegationInviteRouteImport } from './routes/_authenticated/dashboard/_chief/my-delegation/invite'
import { Route as AuthenticatedDashboardAdminDelegationsNewRouteImport } from './routes/_authenticated/dashboard/_admin/delegations/new'
import { Route as AuthenticatedDashboardAdminSportsSportIdIndexRouteImport } from './routes/_authenticated/dashboard/_admin/sports/$sportId/index'
import { Route as AuthenticatedDashboardAdminDelegationsDelegationIdIndexRouteImport } from './routes/_authenticated/dashboard/_admin/delegations/$delegationId/index'
import { Route as AuthenticatedDashboardAdminDelegationsDelegationIdEditRouteImport } from './routes/_authenticated/dashboard/_admin/delegations/$delegationId/edit'
import { Route as AuthenticatedDashboardAdminSportsSportIdModalitiesNewRouteImport } from './routes/_authenticated/dashboard/_admin/sports/$sportId/modalities/new'
import { Route as AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRouteImport } from './routes/_authenticated/dashboard/_admin/sports/$sportId/modalities/$modalityId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestChiefRoute =
  AuthenticatedRequestChiefRouteImport.update({
    id: '/request-chief',
    path: '/request-chief',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/(public)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/(public)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestChiefIndexRoute =
  AuthenticatedRequestChiefIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRequestChiefRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const publicWeeksIndexRoute = publicWeeksIndexRouteImport.update({
  id: '/(public)/weeks/',
  path: '/weeks/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSportsIndexRoute = publicSportsIndexRouteImport.update({
  id: '/(public)/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicResultsIndexRoute = publicResultsIndexRouteImport.update({
  id: '/(public)/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDelegationsIndexRoute = publicDelegationsIndexRouteImport.update({
  id: '/(public)/delegations/',
  path: '/delegations/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCalendarIndexRoute = publicCalendarIndexRouteImport.update({
  id: '/(public)/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestChiefStatusRoute =
  AuthenticatedRequestChiefStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedRequestChiefRoute,
  } as any)
const AuthenticatedDashboardChiefRoute =
  AuthenticatedDashboardChiefRouteImport.update({
    id: '/_chief',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAthletesAthleteIdRoute =
  AuthenticatedAthletesAthleteIdRouteImport.update({
    id: '/athletes/$athleteId',
    path: '/athletes/$athleteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const publicWeeksWeekIdRoute = publicWeeksWeekIdRouteImport.update({
  id: '/(public)/weeks/$weekId',
  path: '/weeks/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSportsSportIdRoute = publicSportsSportIdRouteImport.update({
  id: '/(public)/sports/$sportId',
  path: '/sports/$sportId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDelegationsDelegationIdRoute =
  publicDelegationsDelegationIdRouteImport.update({
    id: '/(public)/delegations/$delegationId',
    path: '/delegations/$delegationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardAthletesIndexRoute =
  AuthenticatedDashboardAthletesIndexRouteImport.update({
    id: '/athletes/',
    path: '/athletes/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAthletesNewRoute =
  AuthenticatedDashboardAthletesNewRouteImport.update({
    id: '/athletes/new',
    path: '/athletes/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChiefMyDelegationIndexRoute =
  AuthenticatedDashboardChiefMyDelegationIndexRouteImport.update({
    id: '/my-delegation/',
    path: '/my-delegation/',
    getParentRoute: () => AuthenticatedDashboardChiefRoute,
  } as any)
const AuthenticatedDashboardAdminSportsIndexRoute =
  AuthenticatedDashboardAdminSportsIndexRouteImport.update({
    id: '/sports/',
    path: '/sports/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminDelegationsIndexRoute =
  AuthenticatedDashboardAdminDelegationsIndexRouteImport.update({
    id: '/delegations/',
    path: '/delegations/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardChiefMyDelegationTransfersRoute =
  AuthenticatedDashboardChiefMyDelegationTransfersRouteImport.update({
    id: '/my-delegation/transfers',
    path: '/my-delegation/transfers',
    getParentRoute: () => AuthenticatedDashboardChiefRoute,
  } as any)
const AuthenticatedDashboardChiefMyDelegationMembersRoute =
  AuthenticatedDashboardChiefMyDelegationMembersRouteImport.update({
    id: '/my-delegation/members',
    path: '/my-delegation/members',
    getParentRoute: () => AuthenticatedDashboardChiefRoute,
  } as any)
const AuthenticatedDashboardChiefMyDelegationInviteRoute =
  AuthenticatedDashboardChiefMyDelegationInviteRouteImport.update({
    id: '/my-delegation/invite',
    path: '/my-delegation/invite',
    getParentRoute: () => AuthenticatedDashboardChiefRoute,
  } as any)
const AuthenticatedDashboardAdminDelegationsNewRoute =
  AuthenticatedDashboardAdminDelegationsNewRouteImport.update({
    id: '/delegations/new',
    path: '/delegations/new',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminSportsSportIdIndexRoute =
  AuthenticatedDashboardAdminSportsSportIdIndexRouteImport.update({
    id: '/sports/$sportId/',
    path: '/sports/$sportId/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute =
  AuthenticatedDashboardAdminDelegationsDelegationIdIndexRouteImport.update({
    id: '/delegations/$delegationId/',
    path: '/delegations/$delegationId/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute =
  AuthenticatedDashboardAdminDelegationsDelegationIdEditRouteImport.update({
    id: '/delegations/$delegationId/edit',
    path: '/delegations/$delegationId/edit',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute =
  AuthenticatedDashboardAdminSportsSportIdModalitiesNewRouteImport.update({
    id: '/sports/$sportId/modalities/new',
    path: '/sports/$sportId/modalities/new',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute =
  AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRouteImport.update(
    {
      id: '/sports/$sportId/modalities/$modalityId/edit',
      path: '/sports/$sportId/modalities/$modalityId/edit',
      getParentRoute: () => AuthenticatedDashboardAdminRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/dashboard': typeof AuthenticatedDashboardChiefRouteWithChildren
  '/request-chief': typeof AuthenticatedRequestChiefRouteWithChildren
  '/delegations/$delegationId': typeof publicDelegationsDelegationIdRoute
  '/sports/$sportId': typeof publicSportsSportIdRoute
  '/weeks/$weekId': typeof publicWeeksWeekIdRoute
  '/athletes/$athleteId': typeof AuthenticatedAthletesAthleteIdRoute
  '/request-chief/status': typeof AuthenticatedRequestChiefStatusRoute
  '/calendar/': typeof publicCalendarIndexRoute
  '/delegations/': typeof publicDelegationsIndexRoute
  '/results/': typeof publicResultsIndexRoute
  '/sports/': typeof publicSportsIndexRoute
  '/weeks/': typeof publicWeeksIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/request-chief/': typeof AuthenticatedRequestChiefIndexRoute
  '/dashboard/athletes/new': typeof AuthenticatedDashboardAthletesNewRoute
  '/dashboard/athletes/': typeof AuthenticatedDashboardAthletesIndexRoute
  '/dashboard/delegations/new': typeof AuthenticatedDashboardAdminDelegationsNewRoute
  '/dashboard/my-delegation/invite': typeof AuthenticatedDashboardChiefMyDelegationInviteRoute
  '/dashboard/my-delegation/members': typeof AuthenticatedDashboardChiefMyDelegationMembersRoute
  '/dashboard/my-delegation/transfers': typeof AuthenticatedDashboardChiefMyDelegationTransfersRoute
  '/dashboard/delegations/': typeof AuthenticatedDashboardAdminDelegationsIndexRoute
  '/dashboard/sports/': typeof AuthenticatedDashboardAdminSportsIndexRoute
  '/dashboard/my-delegation/': typeof AuthenticatedDashboardChiefMyDelegationIndexRoute
  '/dashboard/delegations/$delegationId/edit': typeof AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute
  '/dashboard/delegations/$delegationId/': typeof AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute
  '/dashboard/sports/$sportId/': typeof AuthenticatedDashboardAdminSportsSportIdIndexRoute
  '/dashboard/sports/$sportId/modalities/new': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute
  '/dashboard/sports/$sportId/modalities/$modalityId/edit': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/delegations/$delegationId': typeof publicDelegationsDelegationIdRoute
  '/sports/$sportId': typeof publicSportsSportIdRoute
  '/weeks/$weekId': typeof publicWeeksWeekIdRoute
  '/athletes/$athleteId': typeof AuthenticatedAthletesAthleteIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/request-chief/status': typeof AuthenticatedRequestChiefStatusRoute
  '/calendar': typeof publicCalendarIndexRoute
  '/delegations': typeof publicDelegationsIndexRoute
  '/results': typeof publicResultsIndexRoute
  '/sports': typeof publicSportsIndexRoute
  '/weeks': typeof publicWeeksIndexRoute
  '/request-chief': typeof AuthenticatedRequestChiefIndexRoute
  '/dashboard/athletes/new': typeof AuthenticatedDashboardAthletesNewRoute
  '/dashboard/athletes': typeof AuthenticatedDashboardAthletesIndexRoute
  '/dashboard/delegations/new': typeof AuthenticatedDashboardAdminDelegationsNewRoute
  '/dashboard/my-delegation/invite': typeof AuthenticatedDashboardChiefMyDelegationInviteRoute
  '/dashboard/my-delegation/members': typeof AuthenticatedDashboardChiefMyDelegationMembersRoute
  '/dashboard/my-delegation/transfers': typeof AuthenticatedDashboardChiefMyDelegationTransfersRoute
  '/dashboard/delegations': typeof AuthenticatedDashboardAdminDelegationsIndexRoute
  '/dashboard/sports': typeof AuthenticatedDashboardAdminSportsIndexRoute
  '/dashboard/my-delegation': typeof AuthenticatedDashboardChiefMyDelegationIndexRoute
  '/dashboard/delegations/$delegationId/edit': typeof AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute
  '/dashboard/delegations/$delegationId': typeof AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute
  '/dashboard/sports/$sportId': typeof AuthenticatedDashboardAdminSportsSportIdIndexRoute
  '/dashboard/sports/$sportId/modalities/new': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute
  '/dashboard/sports/$sportId/modalities/$modalityId/edit': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/request-chief': typeof AuthenticatedRequestChiefRouteWithChildren
  '/(public)/delegations/$delegationId': typeof publicDelegationsDelegationIdRoute
  '/(public)/sports/$sportId': typeof publicSportsSportIdRoute
  '/(public)/weeks/$weekId': typeof publicWeeksWeekIdRoute
  '/_authenticated/athletes/$athleteId': typeof AuthenticatedAthletesAthleteIdRoute
  '/_authenticated/dashboard/_admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/_chief': typeof AuthenticatedDashboardChiefRouteWithChildren
  '/_authenticated/request-chief/status': typeof AuthenticatedRequestChiefStatusRoute
  '/(public)/calendar/': typeof publicCalendarIndexRoute
  '/(public)/delegations/': typeof publicDelegationsIndexRoute
  '/(public)/results/': typeof publicResultsIndexRoute
  '/(public)/sports/': typeof publicSportsIndexRoute
  '/(public)/weeks/': typeof publicWeeksIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/request-chief/': typeof AuthenticatedRequestChiefIndexRoute
  '/_authenticated/dashboard/athletes/new': typeof AuthenticatedDashboardAthletesNewRoute
  '/_authenticated/dashboard/athletes/': typeof AuthenticatedDashboardAthletesIndexRoute
  '/_authenticated/dashboard/_admin/delegations/new': typeof AuthenticatedDashboardAdminDelegationsNewRoute
  '/_authenticated/dashboard/_chief/my-delegation/invite': typeof AuthenticatedDashboardChiefMyDelegationInviteRoute
  '/_authenticated/dashboard/_chief/my-delegation/members': typeof AuthenticatedDashboardChiefMyDelegationMembersRoute
  '/_authenticated/dashboard/_chief/my-delegation/transfers': typeof AuthenticatedDashboardChiefMyDelegationTransfersRoute
  '/_authenticated/dashboard/_admin/delegations/': typeof AuthenticatedDashboardAdminDelegationsIndexRoute
  '/_authenticated/dashboard/_admin/sports/': typeof AuthenticatedDashboardAdminSportsIndexRoute
  '/_authenticated/dashboard/_chief/my-delegation/': typeof AuthenticatedDashboardChiefMyDelegationIndexRoute
  '/_authenticated/dashboard/_admin/delegations/$delegationId/edit': typeof AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute
  '/_authenticated/dashboard/_admin/delegations/$delegationId/': typeof AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute
  '/_authenticated/dashboard/_admin/sports/$sportId/': typeof AuthenticatedDashboardAdminSportsSportIdIndexRoute
  '/_authenticated/dashboard/_admin/sports/$sportId/modalities/new': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute
  '/_authenticated/dashboard/_admin/sports/$sportId/modalities/$modalityId/edit': typeof AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/request-chief'
    | '/delegations/$delegationId'
    | '/sports/$sportId'
    | '/weeks/$weekId'
    | '/athletes/$athleteId'
    | '/request-chief/status'
    | '/calendar/'
    | '/delegations/'
    | '/results/'
    | '/sports/'
    | '/weeks/'
    | '/dashboard/'
    | '/request-chief/'
    | '/dashboard/athletes/new'
    | '/dashboard/athletes/'
    | '/dashboard/delegations/new'
    | '/dashboard/my-delegation/invite'
    | '/dashboard/my-delegation/members'
    | '/dashboard/my-delegation/transfers'
    | '/dashboard/delegations/'
    | '/dashboard/sports/'
    | '/dashboard/my-delegation/'
    | '/dashboard/delegations/$delegationId/edit'
    | '/dashboard/delegations/$delegationId/'
    | '/dashboard/sports/$sportId/'
    | '/dashboard/sports/$sportId/modalities/new'
    | '/dashboard/sports/$sportId/modalities/$modalityId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/privacy'
    | '/terms'
    | '/delegations/$delegationId'
    | '/sports/$sportId'
    | '/weeks/$weekId'
    | '/athletes/$athleteId'
    | '/dashboard'
    | '/request-chief/status'
    | '/calendar'
    | '/delegations'
    | '/results'
    | '/sports'
    | '/weeks'
    | '/request-chief'
    | '/dashboard/athletes/new'
    | '/dashboard/athletes'
    | '/dashboard/delegations/new'
    | '/dashboard/my-delegation/invite'
    | '/dashboard/my-delegation/members'
    | '/dashboard/my-delegation/transfers'
    | '/dashboard/delegations'
    | '/dashboard/sports'
    | '/dashboard/my-delegation'
    | '/dashboard/delegations/$delegationId/edit'
    | '/dashboard/delegations/$delegationId'
    | '/dashboard/sports/$sportId'
    | '/dashboard/sports/$sportId/modalities/new'
    | '/dashboard/sports/$sportId/modalities/$modalityId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/request-chief'
    | '/(public)/delegations/$delegationId'
    | '/(public)/sports/$sportId'
    | '/(public)/weeks/$weekId'
    | '/_authenticated/athletes/$athleteId'
    | '/_authenticated/dashboard/_admin'
    | '/_authenticated/dashboard/_chief'
    | '/_authenticated/request-chief/status'
    | '/(public)/calendar/'
    | '/(public)/delegations/'
    | '/(public)/results/'
    | '/(public)/sports/'
    | '/(public)/weeks/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/request-chief/'
    | '/_authenticated/dashboard/athletes/new'
    | '/_authenticated/dashboard/athletes/'
    | '/_authenticated/dashboard/_admin/delegations/new'
    | '/_authenticated/dashboard/_chief/my-delegation/invite'
    | '/_authenticated/dashboard/_chief/my-delegation/members'
    | '/_authenticated/dashboard/_chief/my-delegation/transfers'
    | '/_authenticated/dashboard/_admin/delegations/'
    | '/_authenticated/dashboard/_admin/sports/'
    | '/_authenticated/dashboard/_chief/my-delegation/'
    | '/_authenticated/dashboard/_admin/delegations/$delegationId/edit'
    | '/_authenticated/dashboard/_admin/delegations/$delegationId/'
    | '/_authenticated/dashboard/_admin/sports/$sportId/'
    | '/_authenticated/dashboard/_admin/sports/$sportId/modalities/new'
    | '/_authenticated/dashboard/_admin/sports/$sportId/modalities/$modalityId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicDelegationsDelegationIdRoute: typeof publicDelegationsDelegationIdRoute
  publicSportsSportIdRoute: typeof publicSportsSportIdRoute
  publicWeeksWeekIdRoute: typeof publicWeeksWeekIdRoute
  publicCalendarIndexRoute: typeof publicCalendarIndexRoute
  publicDelegationsIndexRoute: typeof publicDelegationsIndexRoute
  publicResultsIndexRoute: typeof publicResultsIndexRoute
  publicSportsIndexRoute: typeof publicSportsIndexRoute
  publicWeeksIndexRoute: typeof publicWeeksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/request-chief': {
      id: '/_authenticated/request-chief'
      path: '/request-chief'
      fullPath: '/request-chief'
      preLoaderRoute: typeof AuthenticatedRequestChiefRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/request-chief/': {
      id: '/_authenticated/request-chief/'
      path: '/'
      fullPath: '/request-chief/'
      preLoaderRoute: typeof AuthenticatedRequestChiefIndexRouteImport
      parentRoute: typeof AuthenticatedRequestChiefRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/(public)/weeks/': {
      id: '/(public)/weeks/'
      path: '/weeks'
      fullPath: '/weeks/'
      preLoaderRoute: typeof publicWeeksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sports/': {
      id: '/(public)/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof publicSportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/results/': {
      id: '/(public)/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof publicResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/delegations/': {
      id: '/(public)/delegations/'
      path: '/delegations'
      fullPath: '/delegations/'
      preLoaderRoute: typeof publicDelegationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/calendar/': {
      id: '/(public)/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof publicCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/request-chief/status': {
      id: '/_authenticated/request-chief/status'
      path: '/status'
      fullPath: '/request-chief/status'
      preLoaderRoute: typeof AuthenticatedRequestChiefStatusRouteImport
      parentRoute: typeof AuthenticatedRequestChiefRoute
    }
    '/_authenticated/dashboard/_chief': {
      id: '/_authenticated/dashboard/_chief'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardChiefRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/_admin': {
      id: '/_authenticated/dashboard/_admin'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/athletes/$athleteId': {
      id: '/_authenticated/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/weeks/$weekId': {
      id: '/(public)/weeks/$weekId'
      path: '/weeks/$weekId'
      fullPath: '/weeks/$weekId'
      preLoaderRoute: typeof publicWeeksWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sports/$sportId': {
      id: '/(public)/sports/$sportId'
      path: '/sports/$sportId'
      fullPath: '/sports/$sportId'
      preLoaderRoute: typeof publicSportsSportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/delegations/$delegationId': {
      id: '/(public)/delegations/$delegationId'
      path: '/delegations/$delegationId'
      fullPath: '/delegations/$delegationId'
      preLoaderRoute: typeof publicDelegationsDelegationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/athletes/': {
      id: '/_authenticated/dashboard/athletes/'
      path: '/athletes'
      fullPath: '/dashboard/athletes/'
      preLoaderRoute: typeof AuthenticatedDashboardAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/athletes/new': {
      id: '/_authenticated/dashboard/athletes/new'
      path: '/athletes/new'
      fullPath: '/dashboard/athletes/new'
      preLoaderRoute: typeof AuthenticatedDashboardAthletesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/_chief/my-delegation/': {
      id: '/_authenticated/dashboard/_chief/my-delegation/'
      path: '/my-delegation'
      fullPath: '/dashboard/my-delegation/'
      preLoaderRoute: typeof AuthenticatedDashboardChiefMyDelegationIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardChiefRoute
    }
    '/_authenticated/dashboard/_admin/sports/': {
      id: '/_authenticated/dashboard/_admin/sports/'
      path: '/sports'
      fullPath: '/dashboard/sports/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSportsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/delegations/': {
      id: '/_authenticated/dashboard/_admin/delegations/'
      path: '/delegations'
      fullPath: '/dashboard/delegations/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminDelegationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_chief/my-delegation/transfers': {
      id: '/_authenticated/dashboard/_chief/my-delegation/transfers'
      path: '/my-delegation/transfers'
      fullPath: '/dashboard/my-delegation/transfers'
      preLoaderRoute: typeof AuthenticatedDashboardChiefMyDelegationTransfersRouteImport
      parentRoute: typeof AuthenticatedDashboardChiefRoute
    }
    '/_authenticated/dashboard/_chief/my-delegation/members': {
      id: '/_authenticated/dashboard/_chief/my-delegation/members'
      path: '/my-delegation/members'
      fullPath: '/dashboard/my-delegation/members'
      preLoaderRoute: typeof AuthenticatedDashboardChiefMyDelegationMembersRouteImport
      parentRoute: typeof AuthenticatedDashboardChiefRoute
    }
    '/_authenticated/dashboard/_chief/my-delegation/invite': {
      id: '/_authenticated/dashboard/_chief/my-delegation/invite'
      path: '/my-delegation/invite'
      fullPath: '/dashboard/my-delegation/invite'
      preLoaderRoute: typeof AuthenticatedDashboardChiefMyDelegationInviteRouteImport
      parentRoute: typeof AuthenticatedDashboardChiefRoute
    }
    '/_authenticated/dashboard/_admin/delegations/new': {
      id: '/_authenticated/dashboard/_admin/delegations/new'
      path: '/delegations/new'
      fullPath: '/dashboard/delegations/new'
      preLoaderRoute: typeof AuthenticatedDashboardAdminDelegationsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/sports/$sportId/': {
      id: '/_authenticated/dashboard/_admin/sports/$sportId/'
      path: '/sports/$sportId'
      fullPath: '/dashboard/sports/$sportId/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSportsSportIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/delegations/$delegationId/': {
      id: '/_authenticated/dashboard/_admin/delegations/$delegationId/'
      path: '/delegations/$delegationId'
      fullPath: '/dashboard/delegations/$delegationId/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminDelegationsDelegationIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/delegations/$delegationId/edit': {
      id: '/_authenticated/dashboard/_admin/delegations/$delegationId/edit'
      path: '/delegations/$delegationId/edit'
      fullPath: '/dashboard/delegations/$delegationId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardAdminDelegationsDelegationIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/sports/$sportId/modalities/new': {
      id: '/_authenticated/dashboard/_admin/sports/$sportId/modalities/new'
      path: '/sports/$sportId/modalities/new'
      fullPath: '/dashboard/sports/$sportId/modalities/new'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSportsSportIdModalitiesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/_admin/sports/$sportId/modalities/$modalityId/edit': {
      id: '/_authenticated/dashboard/_admin/sports/$sportId/modalities/$modalityId/edit'
      path: '/sports/$sportId/modalities/$modalityId/edit'
      fullPath: '/dashboard/sports/$sportId/modalities/$modalityId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminDelegationsNewRoute: typeof AuthenticatedDashboardAdminDelegationsNewRoute
  AuthenticatedDashboardAdminDelegationsIndexRoute: typeof AuthenticatedDashboardAdminDelegationsIndexRoute
  AuthenticatedDashboardAdminSportsIndexRoute: typeof AuthenticatedDashboardAdminSportsIndexRoute
  AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute: typeof AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute
  AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute: typeof AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute
  AuthenticatedDashboardAdminSportsSportIdIndexRoute: typeof AuthenticatedDashboardAdminSportsSportIdIndexRoute
  AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute: typeof AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute
  AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute: typeof AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminDelegationsNewRoute:
      AuthenticatedDashboardAdminDelegationsNewRoute,
    AuthenticatedDashboardAdminDelegationsIndexRoute:
      AuthenticatedDashboardAdminDelegationsIndexRoute,
    AuthenticatedDashboardAdminSportsIndexRoute:
      AuthenticatedDashboardAdminSportsIndexRoute,
    AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute:
      AuthenticatedDashboardAdminDelegationsDelegationIdEditRoute,
    AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute:
      AuthenticatedDashboardAdminDelegationsDelegationIdIndexRoute,
    AuthenticatedDashboardAdminSportsSportIdIndexRoute:
      AuthenticatedDashboardAdminSportsSportIdIndexRoute,
    AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute:
      AuthenticatedDashboardAdminSportsSportIdModalitiesNewRoute,
    AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute:
      AuthenticatedDashboardAdminSportsSportIdModalitiesModalityIdEditRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedDashboardChiefRouteChildren {
  AuthenticatedDashboardChiefMyDelegationInviteRoute: typeof AuthenticatedDashboardChiefMyDelegationInviteRoute
  AuthenticatedDashboardChiefMyDelegationMembersRoute: typeof AuthenticatedDashboardChiefMyDelegationMembersRoute
  AuthenticatedDashboardChiefMyDelegationTransfersRoute: typeof AuthenticatedDashboardChiefMyDelegationTransfersRoute
  AuthenticatedDashboardChiefMyDelegationIndexRoute: typeof AuthenticatedDashboardChiefMyDelegationIndexRoute
}

const AuthenticatedDashboardChiefRouteChildren: AuthenticatedDashboardChiefRouteChildren =
  {
    AuthenticatedDashboardChiefMyDelegationInviteRoute:
      AuthenticatedDashboardChiefMyDelegationInviteRoute,
    AuthenticatedDashboardChiefMyDelegationMembersRoute:
      AuthenticatedDashboardChiefMyDelegationMembersRoute,
    AuthenticatedDashboardChiefMyDelegationTransfersRoute:
      AuthenticatedDashboardChiefMyDelegationTransfersRoute,
    AuthenticatedDashboardChiefMyDelegationIndexRoute:
      AuthenticatedDashboardChiefMyDelegationIndexRoute,
  }

const AuthenticatedDashboardChiefRouteWithChildren =
  AuthenticatedDashboardChiefRoute._addFileChildren(
    AuthenticatedDashboardChiefRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardChiefRoute: typeof AuthenticatedDashboardChiefRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAthletesNewRoute: typeof AuthenticatedDashboardAthletesNewRoute
  AuthenticatedDashboardAthletesIndexRoute: typeof AuthenticatedDashboardAthletesIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute:
      AuthenticatedDashboardAdminRouteWithChildren,
    AuthenticatedDashboardChiefRoute:
      AuthenticatedDashboardChiefRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAthletesNewRoute:
      AuthenticatedDashboardAthletesNewRoute,
    AuthenticatedDashboardAthletesIndexRoute:
      AuthenticatedDashboardAthletesIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRequestChiefRouteChildren {
  AuthenticatedRequestChiefStatusRoute: typeof AuthenticatedRequestChiefStatusRoute
  AuthenticatedRequestChiefIndexRoute: typeof AuthenticatedRequestChiefIndexRoute
}

const AuthenticatedRequestChiefRouteChildren: AuthenticatedRequestChiefRouteChildren =
  {
    AuthenticatedRequestChiefStatusRoute: AuthenticatedRequestChiefStatusRoute,
    AuthenticatedRequestChiefIndexRoute: AuthenticatedRequestChiefIndexRoute,
  }

const AuthenticatedRequestChiefRouteWithChildren =
  AuthenticatedRequestChiefRoute._addFileChildren(
    AuthenticatedRequestChiefRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedRequestChiefRoute: typeof AuthenticatedRequestChiefRouteWithChildren
  AuthenticatedAthletesAthleteIdRoute: typeof AuthenticatedAthletesAthleteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedRequestChiefRoute: AuthenticatedRequestChiefRouteWithChildren,
  AuthenticatedAthletesAthleteIdRoute: AuthenticatedAthletesAthleteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicDelegationsDelegationIdRoute: publicDelegationsDelegationIdRoute,
  publicSportsSportIdRoute: publicSportsSportIdRoute,
  publicWeeksWeekIdRoute: publicWeeksWeekIdRoute,
  publicCalendarIndexRoute: publicCalendarIndexRoute,
  publicDelegationsIndexRoute: publicDelegationsIndexRoute,
  publicResultsIndexRoute: publicResultsIndexRoute,
  publicSportsIndexRoute: publicSportsIndexRoute,
  publicWeeksIndexRoute: publicWeeksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
