"""add is_active to delegations

Revision ID: 077cc8a0151d
Revises: 860d7d0d74c8
Create Date: 2026-04-19 01:19:15.641506

"""
from typing import Sequence, Union

import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077cc8a0151d'
down_revision: Union[str, Sequence[str], None] = '860d7d0d74c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegations', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delegations', 'is_active')
    # ### end Alembic commands ###
