"""add is_active to sports modalities add sport_statistics_schemas

Revision ID: 14e69bc397ef
Revises: 077cc8a0151d
Create Date: 2026-04-19 01:39:53.829504

"""
from typing import Sequence, Union

import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e69bc397ef'
down_revision: Union[str, Sequence[str], None] = '077cc8a0151d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_statistics_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id')
    )
    op.add_column('modalities', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('sports', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'is_active')
    op.drop_column('modalities', 'is_active')
    op.drop_table('sport_statistics_schemas')
    # ### end Alembic commands ###
