"""add is_active to athletes

Revision ID: 627739ebd29e
Revises: 14e69bc397ef
Create Date: 2026-04-19 01:47:11.295657

"""
from typing import Sequence, Union

import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627739ebd29e'
down_revision: Union[str, Sequence[str], None] = '14e69bc397ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'is_active')
    # ### end Alembic commands ###
