"""drop_is_showcase_from_leagues

Revision ID: cb6469abc2c1
Revises: c5ccce3cc814
Create Date: 2026-04-26 22:45:13.216545

"""

from typing import Sequence, Union

import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb6469abc2c1"
down_revision: Union[str, Sequence[str], None] = "c5ccce3cc814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("leagues", "is_showcase")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
