"""add_delegation_status_and_league_delegation_tables

Revision ID: ef91d2b9ca95
Revises: bcbbe651409c
Create Date: 2026-05-02 23:15:46.322374

"""

from typing import Sequence, Union

import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef91d2b9ca95"
down_revision: Union[str, Sequence[str], None] = "bcbbe651409c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league_participation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delegation_id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INDEPENDENT",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="delegationstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["delegation_id"],
            ["delegations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "delegations",
        sa.Column(
            "status",
            sa.Enum(
                "INDEPENDENT",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="delegationstatus",
            ),
            server_default="INDEPENDENT",
            nullable=False,
        ),
    )
    op.alter_column(
        "delegations", "league_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("delegations", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "delegations", "league_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("delegations", "status")
    op.drop_table("league_participation_requests")
    # ### end Alembic commands ###
